spin_manifest_version = 2

[application]
name = "spin-shim-self"
version = "0.1.0"
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/service1/..."
component = "service1"

[component.service1]
source = "service1/target/service1.wasm"
allowed_outbound_hosts = ["http://self"]
[component.service1.build]
command = "npm run build"
workdir = "service1"

[[trigger.http]]
route = "/service2/..."
component = "service2"

[component.service2]
source = "service2/target/service2.wasm"
[component.service2.build]
command = "npm run build"
workdir = "service2"
